import {Product} from './app/shared/models/Product';
import { Tag } from './app/shared/models/Tag';

export const sample_products: Product[] = [
 
    {
      id: '1',
      name: 'Smartphone',
      price: 699,
      favorite: false,
      origins: ['USA', 'China'],
      stars: 4.5,
      imageUrl: 'assets/product-2.jpg',
      tags: ['Electronics', 'Mobile', 'Gadgets'],
    },
    {
      id: '2',
      name: 'Laptop',
      price: 999,
      favorite: true,
      origins: ['USA', 'China'],
      stars: 4.8,
      imageUrl: 'assets/product-3.jpg',
      tags: ['Electronics', 'Computers', 'Work'],
    },
    {
      id: '3',
      name: 'Running Shoes',
      price: 120,
      favorite: false,
      origins: ['Vietnam', 'Indonesia'],
      stars: 4.2,
      imageUrl: 'assets/product-4.jpg',
      tags: ['Fashion', 'Shoes', 'Sports'],
    },
    {
      id: '4',
      name: 'Watch',
      price: 250,
      favorite: true,
      origins: ['Switzerland'],
      stars: 4.7,
      imageUrl: 'assets/product-1.jpg',
      tags: ['Fashion', 'Accessories', 'Luxury'],
    },
    {
      id: '5',
      name: 'Wireless Earbuds',
      price: 80,
      favorite: false,
      origins: ['China'],
      stars: 4.0,
      imageUrl: 'assets/product-5.jpg',
      tags: ['Electronics', 'Audio', 'Gadgets'],
    },
]

export const sample_tags: Tag[] = [
  { name: 'All', count: 10 },
  { name: 'Electronics', count: 6 },
  { name: 'Fashion', count: 3 },
  { name: 'Home', count: 2 },
  { name: 'Mobile', count: 1 },
  { name: 'Computers', count: 1 },
  { name: 'Shoes', count: 1 },
  { name: 'Accessories', count: 1 },
  { name: 'Audio', count: 1 },
  { name: 'Bags', count: 1 },
  { name: 'Appliances', count: 1 },
  { name: 'Gaming', count: 1 },
  { name: 'Cameras', count: 1 },
  { name: 'Furniture', count: 1 },
  { name: 'Lighting', count: 1 },
  { name: 'Gadgets', count: 2 },
  { name: 'Work', count: 1 },
  { name: 'Sports', count: 1 },
  { name: 'Luxury', count: 1 },
  { name: 'Travel', count: 1 },
  { name: 'Kitchen', count: 1 },
  { name: 'Entertainment', count: 1 },
  { name: 'Photography', count: 1 },
];